transition_function = {
    ('start', '0'): ('first', '1', 'R'),
    ('start', '1'): ('reject', '1', 'R'),
    ('start', ' '): ('reject', '1', 'R'),
    ('first', '0'): ('first', '0', 'R'),
    ('first', '1'): ('check_1_0', '1', 'R'),
    ('first', ' '): ('reject', ' ', 'L'),
    ('check_1_0', '0'): ('reject', '0', 'R'),
    ('check_1_0', '1'): ('check_1_0', '1', 'R'),
    ('check_1_0', ' '): ('zigzac', ' ', 'L'),
    ('zigzac', '0'): ('reject', '0', 'R'),
    ('zigzac', '1'): ('have1', ' ', 'L'),
    ('zigzac', ' '): ('accept', ' ', ' '),
    ('have1', '0'): ('have1', '0', 'L'),
    ('have1', '1'): ('have1', '1', 'L'),
    ('have1', ' '): ('match1', ' ', 'R'),
    ('match1', '0'): ('back', ' ', 'R'),
    ('match1', '1'): ('reject', '1', 'R'),
    ('match1', ' '): ('accept', ' ', ' '),
    ('back', '0'): ('back', '0', 'R'),
    ('back', '1'): ('back', '1', 'R'),
    ('back', ' '): ('zigzac', ' ', 'L'),
    ('accept', '0'): ('accept', '0', 'R'),
    ('accept', '1'): ('accept', '1', 'R'),
    ('accept', ' '): ('accept', ' ', 'R'),
    ('reject', '0'): ('reject', '0', 'R'),
    ('reject', '1'): ('reject', '1', 'R'),
    ('reject', ' '): ('reject', ' ', 'R')
}
